### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dillfrescott** [ltkong218/IFRNet#25]
How does this method compare to ST-MFNet? Does it yield better results would you say?

https://github.com/danielism97/ST-MFNet

**Comment by ltkong218** [comment]
The main differences between IFRNet and ST-MFNet are:
1. IFRNet takes two frames as input, while ST-MFNet takes four frames as input.
2. IFRNet uses only Vimeo90K triplet dataset for training, while ST-MFNet uses Vimeo90K septuplet and BVI-DVC datasets for training.
3. IFRNet is much more efficient and faster than ST-MFNet.

In conclusion, the frame interpolation accuracy of ST-MFNet may be a little higher than IFRNet since it uses additional input frames. However, the accuracy improvement is little when using the same training datasets. Considering the speed and computation, IFRNet achieves better comprehensive VFI performance.

**Comment by dillfrescott** [comment]
Thank you so much for the info! I appreciate it!
